### ISSUE TITLE
Google Play "505" Error

### ISSUE THREAD

**Issue by ssp0929** [NasaGeek/utexas-utilities#37]
Trying to install/update on a Galaxy Note 4 on Android 5.1.1 nets a 505 error.

**Comment by NasaGeek** [comment]
It is likely that this is a Google Play issue and not an app issue. I just recently published an update, which might be causing hiccups. Give it a day or so and update me with whether the error is still occurring.

**Comment by NasaGeek** [comment]
Fixed in 2.0.1
