### ISSUE TITLE
crashes on launch

### ISSUE THREAD

**Issue by matthewdias** [NasaGeek/utexas-utilities#39]
http://i.imgur.com/wglw1rO.png

**Comment by NasaGeek** [comment]
Seen some crash reports like this one show up recently; it's related to the password encryption (thought I had done away with all those issues, but I guess not). I'm guessing re-installing the app doesn't fix anything? Also, did the behavior immediate begin happening after updating?

**Comment by matthewdias** [comment]
Reinstalling didn't help, and I imagine it was right after updating, as it started happening immediately after I restored from a backup, and hadn't updated the app in at least half a week.

**Comment by NasaGeek** [comment]
Would you be able to look a little earlier in the log and see if there is any reference to a "GeneralSecurityException"?

**Comment by matthewdias** [comment]
No dice. All that's there before the RuntimeException is `ClassLoader referenced unknown path: /data/app/com.nasageek.utexasutilities-1/lib/arm64`, and ACR looking for error files.

**Comment by matthewdias** [comment]
Latest update fixed it
