### ISSUE TITLE
Bus route times are broken

### ISSUE THREAD

**Issue by NasaGeek** [NasaGeek/utexas-utilities#41]
CapMetro went and changed their API. It's now hosted by some service called Hafas, and the API is quite complex now... this guy https://github.com/derhuerst has done quite a bit of work understanding the API for a different city's transit system. Who knows if this will ever actually get fixed.

**Comment by abhinavk99** [comment]
Is this still something that needs to be fixed? If so, I'm gonna try to take a crack at it sometime in the future.

**Comment by NasaGeek** [comment]
I have some working code that needs a little more testing/optimization. Hoping to address this and a few other issues by next week. I appreciate the help offer, though!

**Comment by NasaGeek** [comment]
Resolved by f599796491104bd89bd96d4c63de6270c104e076.
